### PR TITLE
Changes to send same parameters to success callback when the toast hides automatically

### PR DESCRIPTION
**Pull request by ElNinjaGaiden**
Sometimes a toast is bind to a notification handled by the backend of your app. Usually there is a "notification id" that you need to "clear" in the backend when you think the notification was delivered, no matter if the user has tapped the toast or not (this will be defined by your own app logic). Whit that said, there is a big chance users will need to know the value of "data" into the success callback when the toast hides from itself.

This PR just send the same data set to the success callback when the toast hides from itself but instead of notify the event as "touch" it uses the word "hide". The toast message and data remains the same.

### CODE REVIEW

**Comment by ElNinjaGaiden** [comment]
This is not working as expected yet for android.

**Comment by ElNinjaGaiden** [comment]
Android support was fixed. Reopening pull request.

**Comment by kosssi** [comment]
It's really a good idea !!!
@ElNinjaGaiden can you rebase your pull request?

:+1:

**Comment by ElNinjaGaiden** [comment]
@kosssi done!

**Comment by EddyVerbruggen** [comment]
Sweet stuff, @ElNinjaGaiden would you mind adding a little explanation/guidance to the readme as well?

**Comment by ElNinjaGaiden** [comment]
@EddyVerbruggen done

**Comment by EddyVerbruggen** [comment]
Supercool! Merged to master - I'll leave it there for a few days so folks can try it and report issues before publishing to npm. Thanks for sharing this feature!

**Comment by kosssi** [comment]
Thanks @ElNinjaGaiden @EddyVerbruggen :dancer:

**Pull request merged**
